### ISSUE TITLE
Is it possible to analyse more than 64 genes?

### ISSUE THREAD

**Issue by burgerga** [swoodhouse/SCNS-Toolkit#3]
I have output with about 12000 genes, is it (or will it ever be) possible to analyse all of them?

**Comment by swoodhouse** [comment]
In principle it would be straightforward to change constructSTG.fsx to handle data sets with more genes. The 64 gene limitation is an optimisation that means we can construct the graph using bit arithmetic on 64 bit integers.

However, as you increase the number of genes you consider the number of cells you need to measure in order to get a connected STG increases significantly. I would recommend using a small gene set to begin with and seeing what the resulting graph looks like.

**Comment by burgerga** [comment]
Thanks for your answer (also on the other issues), much appreciated!
